### ISSUE TITLE
Slow syntax parsing for certain code

### ISSUE THREAD

**Issue by davej** [MadcapJake/language-earl-grey#15]
As an example, try to copy and paste the code below into Atom and change the language to Earl Grey.

```
setup-envs = (defaults) ->
  process.env.MY_PATH_DNS_SRC = defaults.paths.dns.src
  process.env.MY_PATH_DNS_DEST = defaults.paths.dns.dest

  process.env.MY_PATH_FIREWALL_SRC = defaults.paths.firewall.src
  process.env.MY_PATH_FIREWALL_DEST = defaults.paths.firewall.dest
  process.env.MY_PATH_FIREWALL_REF = defaults.paths.firewall.ref
  process.env.MY_PATH_FIREWALL_INSTALLED = defaults.paths.firewall.installed
```

**Comment by MadcapJake** [comment]
Seems to have something to do with how long those `MY_PATH_FIREWALL...` symbols are. The only way I can get it to stop lagging is to change to a nested object pattern:

```
setup-envs = (defaults) ->
  process.env.MY_PATH.DNS_SRC = defaults.paths.dns.src
  process.env.MY_PATH.DNS_DEST = defaults.paths.dns.dest

  process.env.MY_PATH.FIREWALL_SRC = defaults.paths.firewall.src
  process.env.MY_PATH.FIREWALL_DEST = defaults.paths.firewall.dest
  process.env.MY_PATH.FIREWALL_REF = defaults.paths.firewall.ref
  process.env.MY_PATH.FIREWALL_INSTALLED = defaults.paths.firewall.installed
```

Even faster when replacing the innermost underscore with a dot as well. 

I'm not sure what to do to improve that. I was thinking of using a begin/end rule for dot strings and just have the highlighter think that a series of dot-strings is just one long one. Not sure if that will get a performance gain or not though. Long dot-strings in the current rule seem to be what cause the performance drop.  But maybe having fewer longer captures is better than the current method.

I'm a bit stumped if you have any ideas! :confused:

**Comment by davej** [comment]
Yeah, the longer the symbol the slower it takes. As you add extra characters it seems to get twice as slow each time.

I can't really do much to help, it would take too long for me to figure out what all the regex does. I've attached an image of a CPU profile (and source) but I don't think it will help much. You would probably need to whip out the debugger.

![screen shot 2015-06-04 at 15 53 32](https://cloud.githubusercontent.com/assets/26971/7986960/9f70bf62-0ad2-11e5-84e9-8254030b9dc6.png)

[.cpuprofile](http://cl.ly/2D0c3G1a0U40)

**Comment by MadcapJake** [comment]
Yeah I tried that too, not much to gather without knowing the internals of oniguruma's scanner.

A few ideas:
- Maybe it's because I have several dot-related rules.  I could consolidate and use a larger nested pattern with captures for the different types of dotted syntax. Looking over other language grammars for Atom, I've never seen this and it could perform poorly.
- Maybe I have just _too_ much variation on these dot-related symbols.  I could drop the dotted function pattern completely and only capture builtin/support functions.
  - Python captures function calls only as beginners of parameter blocks (no highlighting, dot or not)
  - Javascript doesn't capture function calls; only support functions
  - Coffeescript doesn't capture function calls; only support functions
- I could also leave the dotted function calls but change dotted strings to only capture the last in a chain.
- I could change dotted strings to only capture outside of a chain (free-standing)

**Comment by davej** [comment]
I'm no help to you, I actively avoid using regex in my day-to-day coding. :-)
Perhaps ask on the atom forum: https://discuss.atom.io

**Comment by MadcapJake** [comment]
Well let's just take a step back from the regex :smile: 

Would you want all, only dotted, only support, or no function calls highlighted?

Would you want all, only end of chain, or only free-standing dot-strings highlighted?

@breuleux, do you have a preference?

**Comment by davej** [comment]
I'm not sure to be honest, I'd probably need to see examples.

**Comment by MadcapJake** [comment]
This has been fixed and now only highlights the field being assigned to.
